### ISSUE TITLE
Simple project

### ISSUE THREAD

**Issue by fewensa** [nuxeh/tdlib-sys#2]
Hi, I think this project should not have use bindgen to build td to generate code. because, `tdlib-sys` it's a ffi project to call [td](https://github.com/tdlib/td) (tdlibjson.so), and this API file basically won't change.

https://github.com/tdlib/td/commits/master/td/telegram/td_json_client.h
History of this file.

May we only use the final generate code?

Or you want to publish different system lib to create.io (include *.so/dll file) ? If that, I think need change Cargo.toml to support this feature.

**Comment by nuxeh** [comment]
Yes, I agree. However, the bindgen is contained in a separate crate, so builds and packages separately from `tdlib-sys`, even if it's in the same repository. At least, that was the intention. They are separately published on crates.io.

Actually my main reason for making the bindgen crate was to test the sys crate, and its passing of libs and headers to dependent crates, and so it's available since it's a normal thing to have l. I was aware that perhaps it wouldn't be required in this use case.

If you do want to use bindgen, and indeed if the bindgen in this repo works as expected, sure it can be changed as needed!

**Comment by nuxeh** [comment]
Hi @fewensa , have you had a look at this? I can look at helping with the integration in the next few days

**Comment by fewensa** [comment]
@nuxeh  Yes, I read that, and sorry did not reply to you in time.
In my plain, I want `tdlib-sys` It's a simple project, only have call `libtdjson.so` code, now this project have some dependencies

https://github.com/nuxeh/tdlib-sys/blob/d471636607a6f6e20c2fe2f493440d08f6d28ff0/Cargo.toml#L21-L23

and need to compile, If it is just to do the binding of tdlib in rust, this project is great, but in rtdlib these are redundant and meaningless.


You can see this issue https://github.com/fewensa/telegram-client/issues/6
and this project https://github.com/fewensa/tdlib-dylib  (Not finish now), 


describe by rtdlib that you should find that rtdlib version is follow td, compared to the complex tdlib-sys, I think compiling `.so` file in different system will be more helpful for the use of the project.
So I asked to you:

> Or you want to publish different system lib to create.io (include *.so/dll file) ? If that, I think need change Cargo.toml to support this feature. 

Can you make this project simpler and not dependencies? or create another project. Then change rtdlib and complete tdlib-dylib.
